### ISSUE TITLE
Master javascript fundementals

### ISSUE THREAD

**Issue by riatzukiza** [Gar-Gar23/DuckBot#4]
# Intent

Given what I saw of your current skill, you need to drill basics.
Each one of these contains interactive javascript prompts. You can press the `Try it your self`
button, and you will get an editable javascript program, and a result you can play with in pretty much real time. 
You are encouraged to use this feature, and modify the examples, to cement your understanding of the underlying concepts.

# Goal 

Demonstrate a total understanding of the fundemental concepts of programming, specifically in javascript.

Use thse [Excercises](https://www.w3schools.com/js/js_exercises.asp) to help solidify the concepts
Use this [test](https://www.w3schools.com/js/js_quiz.asp) to guage how well you understand the concepts

# Statements and language behaviors

- [x] [Syntax basics](https://www.w3schools.com/js/js_syntax.asp)
- [x] [Variables](https://www.w3schools.com/js/js_variables.asp)
- [x] [Variable Assignment](https://www.w3schools.com/js/js_assignment.asp)
- [x] [Operators](https://www.w3schools.com/js/js_operators.asp)
- [x] [If... else if... else...](https://www.w3schools.com/js/js_if_else.asp)
- [x] [let statement](https://www.w3schools.com/js/js_let.asp)
- [x] [constants](https://www.w3schools.com/js/js_const.asp)
- [x] [for loops](https://www.w3schools.com/js/js_loop_for.asp)
- [x] [Hoisting](https://www.w3schools.com/js/js_hoisting.asp)
- [x] [scope](https://www.w3schools.com/js/js_scope.asp)

# Functions

- [x] [Functions in javascript](https://www.w3schools.com/js/js_functions.asp)
- [ ] [Function defintions](https://www.w3schools.com/js/js_function_definition.asp)
- [ ] [Function parameters/arguements](https://www.w3schools.com/js/js_function_parameters.asp)
- [ ] [Function invocation](https://www.w3schools.com/js/js_function_invocation.asp)
- [ ] [Arrow Functions](https://www.w3schools.com/js/js_arrow_function.asp)

# Native object types

## Arrays

ordered lists of objects of which values contained with in are index with numbers,
starting with 0.

- [x] [Arrays](https://www.w3schools.com/js/js_arrays.asphttps://www.w3schools.com/Js/js_classes.asp)
- [x] [Array methods](https://www.w3schools.com/js/js_array_methods.asp)
- [ ] [Array Itteration](https://www.w3schools.com/js/js_array_iteration.asp)

## Strings

- [x] [Strings](https://www.w3schools.com/js/js_strings.asp)
- [ ] [String methods](https://www.w3schools.com/js/js_string_methods.asp)

## Regular expressions (RegExp)

- [ ] [RegExp](https://www.w3schools.com/js/js_regexp.asp)

# Objects

- [ ] [Classes](https://www.w3schools.com/Js/js_classes.asp)
- [x] [Object properties](https://www.w3schools.com/js/js_object_properties.asp)
- [ ] [Object methods](https://www.w3schools.com/js/js_object_methods.asp)
- [ ] [JSON](https://www.w3schools.com/js/js_json.asp)

# Best practices and standards 

Some of this is oppinion, but it is a pretty common oppinion, and
a decent place to start forming your own.

- [ ] [Debugging](https://www.w3schools.com/js/js_debugging.asp)
- [ ] [Style](https://www.w3schools.com/js/js_conventions.asp)
- [ ] [General best practices](https://www.w3schools.com/js/js_best_practices.asp)
- [ ] [Common mistakes](https://www.w3schools.com/js/js_mistakes.asp)
